export const actions = Object.freeze({
  SET_CURRENT_USER: "SET_CURRENT_USER",
  UPDATE_USER: "UPDATE_USER",
  OPEN_DIALOG: "OPEN_DIALOG",
  CLOSE_DIALOG: "CLOSE_DIALOG",
  LOGOUT: "LOGOUT",
  LOGIN: "LOGIN",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  CREATE_EXPENSE_FORM_REF: "CREATE_EXPENSE_FORM_REF",
  SEARCH_FILTERS: "SEARCH_FILTERS",
  RESET_FILTERS: "RESET_FILTERS",
  IMAGE_UPLOAD: "IMAGE_UPLOAD",
  REMOVE_IMAGE: "REMOVE_IMAGE",
});
